# Generated by Django 4.0 on 2024-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('products_number', models.IntegerField()),
                ('repetition_interval', models.IntegerField()),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Not Started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeraahAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('products_number', models.IntegerField()),
                ('repetition_interval', models.IntegerField()),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Not Started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('original_price', models.CharField(blank=True, max_length=50, null=True)),
                ('units_sold', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping', models.CharField(blank=True, max_length=50, null=True)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('catygorie', models.CharField(blank=True, max_length=50, null=True)),
                ('scraped_from', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_from', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
