# Generated by Django 4.0 on 2024-02-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('products_number', models.IntegerField()),
                ('repetition_interval', models.IntegerField()),
                ('status', models.CharField(default='Not Started', max_length=20)),
            ],
        ),
    ]
