# Generated by Django 4.0 on 2024-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0002_aliexpressaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliexpressaction',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
