# Generated by Django 4.0 on 2024-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0003_alter_aliexpressaction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scraped_from',
            field=models.URLField(blank=True, null=True),
        ),
    ]
