# Generated by Django 4.0 on 2024-02-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0004_product_scraped_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catygorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
