# Generated by Django 4.0 on 2024-02-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0005_product_catygorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeraahAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('products_number', models.IntegerField()),
                ('repetition_interval', models.IntegerField()),
                ('status', models.CharField(default='Not Started', max_length=20)),
            ],
        ),
    ]
