# Generated by Django 4.0 on 2024-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0007_deraahaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpressaction',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
